site_name: Where.dart
site_description: >
  Find the instances of an executable in the system path, implemented in Dart.
  Like the `which` Linux command.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/where.dart

docs_dir: doc
site_dir: www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/where.dart
edit_uri: ''

copyright: Copyright &copy; 2017 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://belin.io'
    - icon: fontawesome/brands/github
      link: 'https://github.com/cedx'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/cedxbelin'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/cedxbelin'

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage:
      - Programming interface: usage/api.md
      - Command line interface: usage/cli.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  favicon: img/favicon.ico
  palette:
    accent: blue
    primary: blue
