name: where
version: 7.0.0

description: Find the instances of an executable in the system path. Like the `which` Linux command.
homepage: https://docs.belin.io/where.dart
issue_tracker: https://git.belin.io/cedx/where.dart/issues
repository: https://git.belin.io/cedx/where.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  where: where

dependencies:
  build_cli_annotations: ^1.2.0
  path: ^1.7.0

dev_dependencies:
  build_cli: ^1.3.7
  build_runner: ^1.8.1
  build_test: ^1.0.0
  build_version: ^2.0.1
  coverage: ^0.13.9
  grinder: ^0.8.4
  test: ^1.14.2
