name: coveralls
version: 5.9.0

description: Send LCOV and Clover coverage reports to the Coveralls service.
homepage: https://docs.belin.io/coveralls.dart
issue_tracker: https://git.belin.io/cedx/coveralls.dart/issues
repository: https://git.belin.io/cedx/coveralls.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.2.0
  crypto: ^2.1.5
  http: ^0.12.1
  json_annotation: ^3.0.1
  lcov: ^6.0.0
  path: ^1.7.0
  where: ^7.0.0
  xml: ^4.2.0
  yaml: ^2.2.1

dev_dependencies:
  build_cli: ^1.3.9
  build_runner: ^1.10.0
  build_test: ^1.2.0
  build_version: ^2.0.1
  coverage: ^0.14.0
  json_serializable: ^3.3.0
  test: ^1.14.7
