name: common_binaries
version: 0.0.0
private: true

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_vm_compilers: ^1.0.3
  build_web_compilers: ^2.5.1
  built_value_generator: ^7.0.0
  coverage: any
  dart_dev: ^3.0.0
  dart_style: ^1.3.3
  dependency_validator:
    path: ../..
